version: 2.1
jobs:
  build:
    working_directory: ~/client
    docker:
      - image: circleci/node:lts
    pre:
      - rm -rf ~/.yarn
      - npm install -g yarn
      - yarn -v
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run tests
          command: yarn test
