version: 2.1

jobs:
  prebuild:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Build compiled source code
          command: yarn build

  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - prebuild
      - test:
          requires:
            - prebuild
      - build:
          requires:
            - test
