version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  prepare:
    working_directory: ~/client
    executor: node/default
    steps:
      - checkout
      - node/install-yarn
      - node/install-packages:
          app-dir: ~/client
          cache-path: node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn test

  build:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build client
          command: yarn build

  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy client
          command: echo "Deploying client to cloud"

workflows:
  version: 2.1
  test-build-deploy:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - hold:
          type: approval
          requires:
            - test
      - build:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
