version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  prepare-dependencies:
    working_directory: ~/app
    executor:
      name: node/default
      tag: "lts"
    steps:
      - checkout
      - node/install-yarn
      - node/install-packages:
          app-dir: ~/app
          pkg-manager: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    working_directory: ~/app
    executor:
      name: node/default
      tag: "lts"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            mkdir -p ./test-results/junit
            yarn test --ci
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results

  build-source:
    working_directory: ~/app
    executor:
      name: node/default
      tag: "lts"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    working_directory: ~/app
    executor:
      name: node/default
      tag: "lts"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy app
          command: echo "Deploying app to cloud"

workflows:
  version: 2.1
  test-build-deploy:
    jobs:
      - prepare-dependencies
      - test:
          requires:
            - prepare-dependencies
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - build-source:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
