version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  prepare:
    working_directory: ~/client
    executor:
      name: node/default
      tag: "lts"
    steps:
      - checkout
      - node/install-yarn
      - node/install-packages:
          app-dir: ~/client
          pkg-manager: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    working_directory: ~/client
    executor:
      name: node/default
      tag: "lts"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn test
      - store_test_results:
          path: test-results

  build:
    working_directory: ~/client
    executor:
      name: node/default
      tag: "lts"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build client
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    working_directory: ~/client
    executor:
      name: node/default
      tag: "lts"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy client
          command: echo "Deploying client to cloud"

workflows:
  version: 2.1
  test-build-deploy:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
